version: '2'

services:
  postgres:
    image: postgres:11
    restart: unless-stopped
    ports:
      - 54320:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbdata/init:/docker-entrypoint-initdb.d
    env_file:
      - .env.db

  app:
    image: nextcloud:latest
    ports:
      - 8081:81
    links:
      - postgres
    volumes:
      - ./nextcloud:/var/www/html
    restart: unless-stopped
    env_file:
      - .env.app
